### ISSUE TITLE
Example of calling from java?

### ISSUE THREAD

**Issue by jewzaam** [svanoort/rest-compress#1]
Did some reading and not finding the best way to set the headers for this in java.  Specifically using HttpClientBuilder, which seems to be the way to go nowadays.  It's what is being used in [lightblue-client](https://github.com/lightblue-platform/lightblue-client).  See class `LightblueHttpClient` if more context of what is being done is needed.  Might be something set on each request?

**Comment by svanoort** [comment]
Header is "Accept-Encoding: lzf" and can be set when building the HTTPClient.  

After your line: HttpClients.custom(), you would add: setDefaultHeaders(new HashSet<Header>(Arrays.asList({ new BasicHeader("Accept-Encoding","lzf")}))

Docs: http://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/org/apache/http/impl/client/HttpClientBuilder.html

It can also be set on the HTTPMessage or HTTPRequest like so:
message.setHeader(new BasicHeader("Accept-Encoding","lzf"))
