### ISSUE TITLE
The automatic encoding not working in Spring Boot

### ISSUE THREAD

**Issue by daibertdiego** [svanoort/rest-compress#4]
Hi,

I'm trying to use this lib with Spring Boot RESTful Services without success.

I'm using like this:
`  @RequestMapping(path = "/find-by-filter", method = RequestMethod.POST)
    @LZF
    ResponseEntity<?> findByFilter(@RequestBody Filter filter) throws ServiceException {
          ...
     }`

Could you help me?

Congratulations for your job.

Cheers.

**Comment by svanoort** [comment]
@daibertdiego Are you using the RestEasy framework with Spring Boot (it's a RestEasy 2  interceptor)?

You also need to have the client set the accept-encoding header to include LZF:

Header:  `"Accept-Encoding: lzf"`

With curl, this can be tested by adding the argument: curl '-H "Accept-Encoding: lzf"

**Comment by daibertdiego** [comment]
No I don't. I'm using the Default from SpringBoot. The classes has @RequestController like this:

`@RestController
@RequestMapping(path = "/test", consumes = {MediaType.APPLICATION_JSON_VALUE}, produces = {MediaType.APPLICATION_JSON_VALUE})
public class TestResource {`

**Comment by svanoort** [comment]
@daibertdiego That would be why it doesn't work then -- this is an add-on for a different framework.  You'd have to write an implementation specifically for whatever that framework's equivalent of an `Interceptor` is.
